import { FiClock, FiFacebook, FiGlobe, FiInstagram, FiLinkedin, FiMail, FiMapPin, FiMessageCircle, FiPhone, FiSend } from 'react-icons/fi'
import { useSiteSettings } from '../../lib/siteSettings'

export function ContactPage() {
  const settings = useSiteSettings()
  const callHref = `tel:${settings.contact_phone.replace(/[^+\d]/g, '')}`

  return <main className="contact-detail-page" aria-labelledby="contact-page-title">
    <section className="contact-hero"><div><p className="eyebrow">Business Enquiries</p><h1 id="contact-page-title">Let's discuss your manufacturing requirement.</h1><p>Tell us what you need—product, drawing, sample, material, quantity or delivery requirement. The right SKR team can then review your enquiry.</p><a href="#contact-form" className="hero-btn hero-btn-primary">Request a Quote <FiSend /></a></div><div className="image-placeholder contact-image page-visual" role="img" aria-label="SKR factory team and reception"><span>SKR Metal Industries</span><strong>Let's build the right production path.</strong><small>Our team will connect your enquiry with the appropriate specialist division.</small></div></section>
    <section className="contact-info-grid" aria-label="Contact details"><article><FiMail /><div><span>Email us</span><a href={`mailto:${settings.contact_email}`}>{settings.contact_email}</a><small>For product, technical and business enquiries</small></div></article>{settings.contact_phone && <article><FiPhone /><div><span>Call us</span><a href={callHref}>{settings.contact_phone}</a><small>Tap to call the SKR team directly</small></div></article>}<article><FiMapPin /><div><span>Registered office</span><p>{settings.contact_address}</p></div></article><article><FiClock /><div><span>Response process</span><p>{settings.contact_response}</p></div></article></section>
    <section className="contact-channel-section"><div className="contact-map" role="img" aria-label="Map location for SKR Metal Industries in Falna, Rajasthan"><div><FiMapPin /><strong>Falna, Rajasthan</strong><span>India</span></div><a href="https://www.google.com/maps/search/?api=1&query=A-36%2C%20Rana%20Pratap%20Marg%20Industrial%20Area%2C%20Falna%2C%20Pali%2C%20Rajasthan%20306116" target="_blank" rel="noreferrer">Open Google Maps</a></div><div className="contact-channels"><p className="eyebrow">Connect with SKR</p><h2>Choose the right channel for your requirement.</h2><div>{settings.contact_phone && <article><FiPhone /><span><b>Phone</b><a href={callHref}>{settings.contact_phone}</a><small>Tap the number to call us directly.</small></span></article>}<article><FiClock /><span><b>Business hours</b><small>{settings.business_hours}</small></span></article><article><FiGlobe /><span><b>Export enquiries</b><small>Include your country, product details and expected quantity in the enquiry.</small></span></article></div><nav className="contact-socials" aria-label="SKR social channels"><a href="#contact" aria-label="LinkedIn"><FiLinkedin /></a><a href="#contact" aria-label="Facebook"><FiFacebook /></a><a href="#contact" aria-label="Instagram"><FiInstagram /></a><a href={`mailto:${settings.contact_email}`} aria-label="Email SKR"><FiMessageCircle /></a></nav></div></section>
    <section className="contact-quote-banner"><div><p className="eyebrow">Request a Quote</p><h2>Ready to share your requirement?</h2><p>Send your drawing, material, quantity and delivery details to start the right conversation.</p></div><a href="#contact-form" className="hero-btn hero-btn-primary">Open enquiry form <FiSend /></a></section>
  </main>
}
