import { useState } from 'react'
import { FiArrowUpRight, FiDownload, FiSearch } from 'react-icons/fi'
import { operations } from '../../data/operations'

export function OperationsPage({ page }: { page: string }) {
  const data = operations[page]
  const [filter, setFilter] = useState('All')
  const [query, setQuery] = useState('')
  const items = data.items.filter((item) => (filter === 'All' || item.meta.includes(filter) || item.title.includes(filter)) && item.title.toLowerCase().includes(query.toLowerCase()))
  return <main className="operations-page"><section className="operations-hero"><p className="eyebrow">{data.eyebrow}</p><p className="breadcrumb">Home <span>/</span> {data.eyebrow}</p><h1>{data.title}</h1><p>{data.description}</p><a href="#contact" className="hero-btn hero-btn-primary">Talk to our team <FiArrowUpRight /></a></section><section className="operations-controls"><label><FiSearch /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Search ${data.eyebrow.toLowerCase()}`} /></label><div>{data.categories.map((category) => <button key={category} className={filter === category ? 'active' : ''} onClick={() => setFilter(category)}>{category}</button>)}</div></section><section className="operations-grid">{items.map((item, index) => <article key={item.title}><span>0{index + 1}</span><p>{item.meta}</p><h2>{item.title}</h2><p>{item.description}</p><a href="#contact">Learn more <FiArrowUpRight /></a></article>)}</section><section className="operations-process"><div><p className="eyebrow">Our Approach</p><h2>A clear, controlled path.</h2></div><div>{data.process.map((step, index) => <article key={step}><b>0{index + 1}</b><span>{step}</span></article>)}</div></section>{page === 'careers' && <section className="operations-apply"><div><p className="eyebrow">Work Culture & Benefits</p><h2>Bring your skills to meaningful industrial work.</h2><p>Share your role preference, experience and resume through our enquiry form.</p></div><a href="#contact" className="hero-btn hero-btn-primary">Apply now <FiArrowUpRight /></a></section>}{page === 'downloads' && <section className="operations-apply"><div><p className="eyebrow">Document Request</p><h2>Need a specific technical document?</h2><p>Tell us the product or requirement and we will share the appropriate approved material.</p></div><a href="#contact" className="hero-btn hero-btn-primary"><FiDownload /> Request document</a></section>}</main>
}
