import { useMemo, useState } from 'react'
import { FiActivity, FiArrowUpRight, FiCheckCircle, FiDownload, FiFileText, FiSearch, FiShield, FiUsers } from 'react-icons/fi'
import { operations } from '../../data/operations'

const resourcePages = new Set(['clients', 'blog', 'news', 'careers', 'downloads'])
const pageVisuals: Record<string, [string, string, string]> = {
  manufacturing: ['01', 'Material → dispatch', 'Connected production flow'], infrastructure: ['02', 'Built for continuity', 'Systems that support output'], machinery: ['03', 'Process-ready equipment', 'Tooling and machine support'], quality: ['04', 'Quality checkpoints', 'Verification at each stage'], certifications: ['05', 'Approved records', 'Compliance document library'], industries: ['06', 'Application-led supply', 'Production support by industry'], clients: ['01', 'Partnership stories', 'Approved collaboration records'], blog: ['02', 'Knowledge library', 'Practical manufacturing insights'], news: ['03', 'Official updates', 'Company and capability notices'], careers: ['04', 'Build with SKR', 'Open roles and work culture'], downloads: ['05', 'Document desk', 'Company and technical resources'],
}

const pageGuides: Record<string, { label: string; title: string; description: string; points: string[]; tags: string[]; action: string }> = {
  manufacturing: { label: 'Factory readiness', title: 'Plan the right production route before work starts.', description: 'A practical production brief lets the team align material flow, tooling, quality checks and packing requirements around your component.', points: ['Part drawing, sample or clear specification', 'Material grade, finish and quantity requirement', 'Packaging, labelling and delivery expectations'], tags: ['Material flow', 'Tooling support', 'Dispatch planning'], action: 'Share your production brief' },
  infrastructure: { label: 'Operational support', title: 'Infrastructure that keeps the work moving.', description: 'The facility is organised around the essentials that help a manufacturing program remain visible, safe and ready for its next stage.', points: ['Machine-shop and workstation requirements', 'Utility, handling and storage considerations', 'Preventive maintenance and process continuity'], tags: ['Production support', 'Storage planning', 'Safe operations'], action: 'Discuss facility support' },
  machinery: { label: 'Machine selection', title: 'Match the process to the part.', description: 'Machine selection should follow the drawing, tolerance, material and repeat-volume requirement—not a one-size-fits-all route.', points: ['Share drawing, material and critical dimensions', 'Identify repeat quantity and process operations', 'Confirm inspection points before production planning'], tags: ['Forming', 'CNC machining', 'Inspection'], action: 'Review my component' },
  quality: { label: 'Quality planning', title: 'Make the acceptance criteria clear early.', description: 'A clear review of the specification helps set the checkpoints, records and release criteria appropriate to the enquiry.', points: ['Critical dimensions and visual acceptance criteria', 'Required inspection or test documentation', 'Packing and final-release expectations'], tags: ['In-process checks', 'Final review', 'Documentation'], action: 'Plan quality requirements' },
  certifications: { label: 'Document control', title: 'Request only the records relevant to your need.', description: 'Certificate and compliance information is shared through an approved, requirement-led document process.', points: ['Specify the document or compliance requirement', 'Include product or customer-program context', 'Receive the appropriate approved record'], tags: ['Quality records', 'Compliance', 'Validity review'], action: 'Request a document' },
  industries: { label: 'Application review', title: 'Turn application needs into a production brief.', description: 'The best manufacturing route begins with the part’s function, operating environment and commercial requirement.', points: ['Application, drawing and component function', 'Material, finish and performance expectations', 'Prototype, repeat order or supply-program requirement'], tags: ['OEM supply', 'Custom components', 'Engineering support'], action: 'Discuss an application' },
  clients: { label: 'Partnership desk', title: 'A clearer start for every manufacturing partnership.', description: 'Share enough context for the relevant SKR team to understand the program and respond with the right next step.', points: ['Company and application background', 'Component, drawing or sourcing requirement', 'Expected volume, timing and delivery location'], tags: ['OEM programs', 'Custom development', 'Export enquiries'], action: 'Start a conversation' },
  blog: { label: 'Knowledge desk', title: 'Useful manufacturing information, without the noise.', description: 'Use these articles to prepare better sourcing and engineering conversations with the right context.', points: ['Browse by engineering, quality or component topic', 'Use checklists before sending an enquiry', 'Contact the team for requirement-specific guidance'], tags: ['Engineering', 'Quality', 'Sourcing'], action: 'Ask a technical question' },
  news: { label: 'Official updates', title: 'Factory updates with context.', description: 'This space is for approved announcements about capability, infrastructure, quality and industry activity.', points: ['Updates are published after internal confirmation', 'Capability notices explain the relevant application', 'Contact the team for current requirement discussions'], tags: ['Factory progress', 'Capabilities', 'Events'], action: 'Make an enquiry' },
  careers: { label: 'Candidate guide', title: 'Apply with the details that help us evaluate your fit.', description: 'Tell us the production, quality, engineering or support role you are seeking and the experience you bring.', points: ['Role preference and current location', 'Relevant machine, quality or production experience', 'Resume and availability to join'], tags: ['Production', 'Quality', 'Engineering'], action: 'Submit your application' },
  downloads: { label: 'Document desk', title: 'Get the right approved file for your review.', description: 'Choose the document category, tell us your application, and the team can share the appropriate approved material.', points: ['Document name or category required', 'Company and application context', 'Any technical or compliance requirement'], tags: ['Company profile', 'Catalogues', 'Technical documents'], action: 'Request approved material' },
}

export function OperationsPage({ page }: { page: string }) {
  const data = operations[page]
  const [filter, setFilter] = useState('All')
  const [query, setQuery] = useState('')
  const isResource = resourcePages.has(page)
  const visual = pageVisuals[page] ?? ['01', 'SKR Operations', 'Production support']
  const guide = pageGuides[page]
  const items = useMemo(() => data.items.filter((item) => (filter === 'All' || item.meta.includes(filter) || item.title.includes(filter)) && `${item.title} ${item.description}`.toLowerCase().includes(query.toLowerCase())), [data.items, filter, query])
  const icon = isResource ? <FiFileText /> : page === 'quality' || page === 'certifications' ? <FiShield /> : <FiActivity />

  return <main className={`operations-page advanced-operations ${isResource ? 'resource-hub' : 'capability-hub'}`}>
    <section className="operations-hero advanced-operations-hero"><div><p className="eyebrow">{data.eyebrow}</p><p className="breadcrumb">Home <span>/</span> {data.eyebrow}</p><h1>{data.title}</h1><p>{data.description}</p><a href="#contact-form" className="hero-btn hero-btn-primary">Talk to our team <FiArrowUpRight /></a></div><aside className="operations-hero-panel"><span>{visual[0]}</span>{icon}<p>{visual[1]}</p><strong>{visual[2]}</strong><small>{data.items.length} focused areas available</small></aside></section>
    <section className="operations-highlight-strip"><article><FiCheckCircle /><span><b>{data.items.length}</b> Focus areas</span></article><article><FiUsers /><span><b>{data.categories.length - 1}</b> Browse categories</span></article><article><FiActivity /><span><b>01</b> Dedicated team</span></article></section>
    <section className="operations-guide" aria-label={`${data.eyebrow} enquiry guide`}><div className="operations-guide-copy"><p className="eyebrow">{guide.label}</p><h2>{guide.title}</h2><p>{guide.description}</p><a href="#contact-form">{guide.action} <FiArrowUpRight /></a></div><div className="operations-guide-detail"><p>What to include</p><ul>{guide.points.map((point) => <li key={point}><FiCheckCircle />{point}</li>)}</ul><div>{guide.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></div></section>
    <section className="operations-controls"><label><FiSearch /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Search ${data.eyebrow.toLowerCase()}`} /></label><div>{data.categories.map((category) => <button key={category} className={filter === category ? 'active' : ''} onClick={() => setFilter(category)}>{category}</button>)}</div></section>
    <section className="operations-grid advanced-operations-grid">{items.map((item, index) => <article key={item.title}><div className="operations-card-top"><span>{String(index + 1).padStart(2, '0')}</span><em>{item.meta}</em></div><h2>{item.title}</h2><p>{item.description}</p><a href="#contact-form">{isResource ? 'Explore resource' : 'Discuss this capability'} <FiArrowUpRight /></a></article>)}{!items.length && <p className="operations-empty">No matching result. Try another category or search term.</p>}</section>
    <section className="operations-insight"><div><p className="eyebrow">{isResource ? 'Resource journey' : 'Operational method'}</p><h2>{isResource ? 'Information, made easier to use.' : 'A controlled path from requirement to output.'}</h2><p>{isResource ? 'Each section is organised to help customers, candidates and partners find the relevant approved information quickly.' : 'The right capability is selected, prepared and reviewed around the specific product or production requirement.'}</p></div><div>{data.process.map((step, index) => <article key={step}><b>0{index + 1}</b><span>{step}</span></article>)}</div></section>
    {page === 'careers' && <section className="operations-apply"><div><p className="eyebrow">Work Culture & Benefits</p><h2>Bring your skills to meaningful industrial work.</h2><p>Share your role preference, experience and resume through our enquiry form.</p></div><a href="#contact-form" className="hero-btn hero-btn-primary">Apply now <FiArrowUpRight /></a></section>}
    {page === 'downloads' && <section className="operations-apply"><div><p className="eyebrow">Document Request</p><h2>Need a specific technical document?</h2><p>Tell us the product or requirement and we will share the appropriate approved material.</p></div><a href="#contact-form" className="hero-btn hero-btn-primary"><FiDownload /> Request document</a></section>}
  </main>
}
