import { useRef, useState } from 'react'
import { FiArrowLeft, FiArrowUpRight, FiCheck, FiDownload, FiFileText, FiMaximize2, FiPackage, FiSend } from 'react-icons/fi'

type Product = { code: string; name: string; material: string; category: string; description: string; application: string; finish: string; size: string; process: string[] }
const umbrella = (code: string, name: string, description: string, application: string, size: string, forming: string): Product => ({ code, name, description, application, size, category: 'Umbrella Components', material: 'Steel / Aluminium options', finish: 'Plated, powder coated or custom finish', process: ['Material selection', forming, 'Frame assembly', 'Function inspection'] })
const engineering = (code: string, name: string, description: string, application: string, material = 'MS / SS / Aluminium', process = 'CNC / VMC machining'): Product => ({ code, name, description, application, material, process: ['Drawing review', process, 'Surface finish', 'Inspection & dispatch'], category: 'Engineering Components', finish: 'Machined, plated, powder coated or custom', size: 'As per approved drawing' })
const catalogue: Record<string, Product> = {
  'uf-201': umbrella('UF-201', '2 Fold Umbrella Frame', 'A compact folding frame designed for strength, flexibility and smooth opening performance.', 'Compact umbrellas, promotional umbrellas and private-label programmes', 'Custom canopy diameter and shaft length', 'Rib forming'),
  'uf-301': umbrella('UF-301', '3 Fold Umbrella Frame', 'A precision-made three-fold frame developed for convenient carry and dependable everyday use.', 'Travel umbrellas and compact retail umbrella systems', 'Custom folded length and canopy size', 'Multi-fold forming'),
  'uf-401': umbrella('UF-401', 'Solid Umbrella Frame', 'A durable rigid-frame construction for reliable performance in a stable, non-folding format.', 'Classic umbrellas, hospitality and promotional programmes', 'Custom shaft length and rib count', 'Tube processing'),
  'uf-501': umbrella('UF-501', 'Piano Umbrella Frame', 'A smooth functional frame designed for consistent production and stable opening action.', 'Fashion, retail and custom umbrella systems', 'Custom diameter and handle interface', 'Precision forming'),
  'uf-601': umbrella('UF-601', 'Golf Umbrella Frame', 'A large-format umbrella frame engineered for strength, coverage and outdoor stability.', 'Golf umbrellas, corporate gifts and outdoor hospitality', 'Large canopy diameters available', 'Heavy-duty forming'),
  'eh-101': engineering('EH-101', 'ATM Machine Parts', 'Drawing-led precision metal components for ATM assemblies where fit, finish and repeatability matter.', 'ATM enclosures, mechanisms and internal assemblies'),
  'eh-201': engineering('EH-201', 'Printer Components', 'Accurate components manufactured to support reliable printer assembly, alignment and operating performance.', 'Commercial and industrial printer assemblies'),
  'eh-301': engineering('EH-301', 'Valve Fittings', 'Machined valve and fitting components for controlled connection, flow and sealing applications.', 'Industrial valve systems and fluid-handling equipment', 'Brass / SS / MS', 'Precision machining'),
  'eh-401': engineering('EH-401', 'Control Panel Components', 'Custom metal parts for electrical and control-panel applications, manufactured around approved fitment requirements.', 'Electrical panels, cabinets and control assemblies', 'CRCA / MS / SS', 'Cutting & forming'),
  'eh-501': engineering('EH-501', 'Pressure Gauge Meter Parts', 'Precision components for pressure instrumentation where dimensional control and clean finishing matter.', 'Pressure gauges, meters and instrumentation', 'Brass / SS / Aluminium', 'Precision machining'),
  'eh-601': engineering('EH-601', 'Hardware Joineries', 'Reliable hardware and joinery components produced for industrial assemblies and practical installation requirements.', 'Furniture hardware, fixtures and industrial assemblies', 'MS / SS / Aluminium', 'Machining / forming'),
  'eh-701': engineering('EH-701', 'Custom Engineered Components', 'Custom components manufactured from technical drawings, samples or a clear production specification.', 'OEM equipment, industrial machinery and specialised projects', 'Material as specified', 'Process planning'),
}

export function ProductDetailPage({ productId }: { productId: string }) {
  const product = catalogue[productId]
  const [activeImage, setActiveImage] = useState(0)
  const dragStart = useRef<number | null>(null)
  if (!product) return <main className="not-found-page"><p className="eyebrow">Product Not Found</p><h1>This product is not published yet.</h1><p>Please browse the current catalogue or contact SKR with your component requirement.</p><div><a href="#products" className="hero-btn hero-btn-primary">Browse products</a></div></main>
  const isUmbrella = product.category === 'Umbrella Components'
  const galleryViews = ['Component overview', 'Detail & finish', 'Quality checkpoint']
  const specs = [['Product code', product.code], ['Category', product.category], ['Material', product.material], ['Length / size', product.size], ['Finish', product.finish], ['MOQ', 'Discuss with our sales team'], ['Quality standard', 'As per approved requirement']]
  const related = Object.values(catalogue).filter((item) => item.code !== product.code && item.category === product.category).slice(0, 3)
  const changeView = (direction: number) => setActiveImage((current) => (current + direction + galleryViews.length) % galleryViews.length)
  const handlePointerDown = (event: React.PointerEvent<HTMLDivElement>) => {
    dragStart.current = event.clientX
    event.currentTarget.setPointerCapture(event.pointerId)
  }
  const handlePointerUp = (event: React.PointerEvent<HTMLDivElement>) => {
    if (dragStart.current === null) return
    const movement = event.clientX - dragStart.current
    if (Math.abs(movement) > 28) changeView(movement > 0 ? -1 : 1)
    dragStart.current = null
  }
  return <main className={`product-detail-page ${isUmbrella ? 'umbrella-product' : 'engineering-product'}`}>
    <a className="back-link" href="#products"><FiArrowLeft /> Back to products</a>
    <section className="product-detail-hero"><div className="product-gallery"><div className={`product-main-visual product-view-${activeImage}`} role="button" tabIndex={0} aria-label={`${galleryViews[activeImage]}. Drag horizontally to change view.`} onPointerDown={handlePointerDown} onPointerUp={handlePointerUp} onKeyDown={(event) => { if (event.key === 'ArrowLeft') changeView(-1); if (event.key === 'ArrowRight') changeView(1) }}><span>{product.category}</span><strong>{product.code}</strong><small>{galleryViews[activeImage]}</small><FiMaximize2 /><i>Drag to rotate</i></div><div className="product-thumbnails">{galleryViews.map((view, item) => <button type="button" key={view} onClick={() => setActiveImage(item)} className={activeImage === item ? 'active' : ''} aria-label={`View ${view}`}><span>0{item + 1}</span></button>)}<button type="button" className="view-360" onClick={() => changeView(1)} aria-label="Rotate product view">360 deg</button></div></div><div className="product-summary"><p className="eyebrow">{product.category}</p><p className="product-code">{product.code}</p><h1>{product.name}</h1><p>{product.description}</p><div className="product-quick-specs"><span><b>Material</b>{product.material}</span><span><b>Finish</b>{product.finish}</span><span><b>Application</b>{product.application}</span></div><div className="product-actions"><a href="#contact" className="hero-btn hero-btn-primary">Request a quote <FiArrowUpRight /></a><a href="#contact" className="outline-button"><FiDownload /> Request PDF</a></div></div></section>
    <section className="detail-feature-grid"><article><FiCheck /><h3>Key features</h3><p>Designed around functional fit, production repeatability and finish expectations.</p></article><article><FiPackage /><h3>Packaging</h3><p>Protected packing planned around component type, quantity and dispatch route.</p></article><article><FiFileText /><h3>Documentation</h3><p>Technical and commercial documents shared for approved enquiries.</p></article></section>
    <section className="product-content-grid"><div><p className="eyebrow">Technical Details</p><h2>Specification overview.</h2><div className="specification-table">{specs.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></div><aside><p className="eyebrow">Applications</p><h3>Built for real-world use.</h3><p>{product.application}</p><ul><li>Custom dimensions and options available</li><li>Finish selected to meet the application need</li><li>Production capacity discussed against requirement</li></ul></aside></section>
    <section className="product-process"><div><p className="eyebrow">{isUmbrella ? 'Manufacturing Process' : 'Engineering Process'}</p><h2>From specification to supply.</h2></div><div>{product.process.map((step, index) => <article key={step}><b>0{index + 1}</b><span>{step}</span></article>)}</div></section>
    <section className="product-faq" aria-labelledby="product-faq-title"><div><p className="eyebrow">Product FAQ</p><h2 id="product-faq-title">Before you request a quote.</h2><p>These answers help you prepare the technical details our team needs for a faster review.</p></div><div>{[['What should I share for a quote?', 'Send a drawing or sample, required material, quantity, finish, application and delivery location.'], ['Can I request a custom size or finish?', 'Yes. Add the required dimensions and finish to your enquiry so the team can review feasibility.'], ['Can technical documents be requested?', 'Approved documents can be requested through the quote form with your product and application context.']].map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section>
    <section className="related-products"><div className="section-title"><div><p className="eyebrow">Related Products</p><h2>Explore more from this range.</h2></div><a href="#products" className="text-link">All products <FiArrowUpRight /></a></div><div>{related.map((item) => <a href={`#product-${item.code.toLowerCase()}`} key={item.code}><span>{item.code}</span><h3>{item.name}</h3><p>{item.material}</p><FiArrowUpRight /></a>)}</div></section>
    <section className="product-enquiry"><div><p className="eyebrow">Need a Custom Version?</p><h2>Share your drawing, sample or requirement.</h2><p>We can review size, material, finish, quantity, packaging and quality expectations with you.</p></div><a href="#contact-form" className="hero-btn hero-btn-primary">Start an enquiry <FiArrowUpRight /></a></section><a className="product-sticky-quote" href="#contact-form"><FiSend /> Request a quote</a>
  </main>
}
