import { useState } from 'react'
import { FiArrowLeft, FiArrowUpRight, FiCheck, FiDownload, FiFileText, FiMaximize2, FiPackage } from 'react-icons/fi'

type Product = { code: string; name: string; material: string; category: string; description: string; application: string; finish: string }
const catalogue: Record<string, Product> = {
  'ur-101': { code: 'UR-101', name: 'Umbrella Rib', material: 'Carbon Steel / Stainless Steel', category: 'Umbrella Components', description: 'A production-focused umbrella rib component engineered for consistent forming, functional fit and dependable assembly performance.', application: 'Umbrella frames, compact umbrellas and custom canopy systems', finish: 'Zinc plated / powder coated / custom finish' },
  'uf-210': { code: 'UF-210', name: 'Umbrella Frame', material: 'Steel', category: 'Umbrella Components', description: 'A configurable umbrella frame assembly developed around the required geometry, opening action and finish requirement.', application: 'Standard, promotional and custom umbrella systems', finish: 'Powder coated / plated finish' },
  've-320': { code: 'VE-320', name: 'Precision Turned Part', material: 'MS / SS / Aluminium', category: 'Engineering Components', description: 'A drawing-led precision turned component for industrial applications where dimensional control and surface finish matter.', application: 'Automotive, OEM and industrial equipment', finish: 'Machined / polished / custom surface treatment' },
  've-410': { code: 'VE-410', name: 'Sheet Metal Bracket', material: 'CRCA / MS / SS', category: 'Engineering Components', description: 'A formed sheet-metal bracket produced against approved dimensions, material and installation requirements.', application: 'Industrial assemblies, machinery and OEM products', finish: 'Powder coated / plated / raw' },
  'ur-511': { code: 'UR-511', name: 'Runner Assembly', material: 'Steel', category: 'Umbrella Components', description: 'An umbrella runner assembly designed for repeatable movement, secure fit and efficient integration into the frame.', application: 'Manual and semi-automatic umbrella frames', finish: 'Zinc plated / painted' },
  've-630': { code: 'VE-630', name: 'Fabricated Component', material: 'Mild Steel', category: 'Engineering Components', description: 'A fabrication-oriented component manufactured through an agreed cutting, forming, welding and finishing route.', application: 'Industrial equipment and custom engineering projects', finish: 'Welded / painted / powder coated' },
}

export function ProductDetailPage({ productId }: { productId: string }) {
  const product = catalogue[productId]
  const [activeImage, setActiveImage] = useState(0)
  if (!product) return <main className="not-found-page"><p className="eyebrow">Product Not Found</p><h1>This product is not published yet.</h1><p>Please browse the current catalogue or contact SKR with your component requirement.</p><div><a href="#products" className="hero-btn hero-btn-primary">Browse products</a></div></main>
  const isUmbrella = product.category === 'Umbrella Components'
  const galleryViews = ['Component overview', 'Detail & finish', 'Quality checkpoint']
  const specs = [['Product code', product.code], ['Category', product.category], ['Material', product.material], ['Thickness', 'As per approved specification'], ['Length / size', 'Custom options available'], ['Finish', product.finish], ['MOQ', 'Discuss with our sales team'], ['Quality standard', 'As per approved requirement']]
  return <main className="product-detail-page">
    <a className="back-link" href="#products"><FiArrowLeft /> Back to products</a>
    <section className="product-detail-hero"><div className="product-gallery"><div className={`product-main-visual product-view-${activeImage}`} aria-label={galleryViews[activeImage]}><span>{product.category}</span><strong>{product.code}</strong><small>{galleryViews[activeImage]}</small><FiMaximize2 /></div><div className="product-thumbnails">{galleryViews.map((view, item) => <button key={view} onClick={() => setActiveImage(item)} className={activeImage === item ? 'active' : ''} aria-label={`View ${view}`}><span>0{item + 1}</span></button>)}<button className="view-360" onClick={() => setActiveImage((current) => (current + 1) % galleryViews.length)} aria-label="Change product view">360°</button></div></div><div className="product-summary"><p className="eyebrow">{product.category}</p><p className="product-code">{product.code}</p><h1>{product.name}</h1><p>{product.description}</p><div className="product-quick-specs"><span><b>Material</b>{product.material}</span><span><b>Finish</b>{product.finish}</span><span><b>Application</b>{product.application}</span></div><div className="product-actions"><a href="#contact" className="hero-btn hero-btn-primary">Request a quote <FiArrowUpRight /></a><a href="#downloads" className="outline-button"><FiDownload /> Request PDF</a></div></div></section>
    <section className="detail-feature-grid"><article><FiCheck /><h3>Key features</h3><p>Designed around functional fit, production repeatability and finish expectations.</p></article><article><FiPackage /><h3>Packaging</h3><p>Protected packing planned around component type, quantity and dispatch route.</p></article><article><FiFileText /><h3>Documentation</h3><p>Technical and commercial documents shared for approved enquiries.</p></article></section>
    <section className="product-content-grid"><div><p className="eyebrow">Technical Details</p><h2>Specification overview.</h2><div className="specification-table">{specs.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></div><aside><p className="eyebrow">Applications</p><h3>Built for real-world use.</h3><p>{product.application}</p><ul><li>Custom dimensions and options available</li><li>Finish selected to meet the application need</li><li>Production capacity discussed against requirement</li></ul></aside></section>
    <section className="product-process"><div><p className="eyebrow">{isUmbrella ? 'Manufacturing Process' : 'Engineering Process'}</p><h2>From specification to supply.</h2></div><div>{(isUmbrella ? ['Material review', 'Cutting & forming', 'Assembly', 'Inspection'] : ['Drawing review', 'Machining / fabrication', 'Surface finish', 'Inspection & dispatch']).map((step, index) => <article key={step}><b>0{index + 1}</b><span>{step}</span></article>)}</div></section>
    <section className="related-products"><div className="section-title"><div><p className="eyebrow">Related Products</p><h2>Explore more from this range.</h2></div><a href="#products" className="text-link">All products <FiArrowUpRight /></a></div><div>{Object.values(catalogue).filter((item) => item.code !== product.code && item.category === product.category).slice(0, 3).map((item) => <a href={`#product-${item.code.toLowerCase()}`} key={item.code}><span>{item.code}</span><h3>{item.name}</h3><p>{item.material}</p><FiArrowUpRight /></a>)}</div></section>
    <section className="product-enquiry"><div><p className="eyebrow">Need a Custom Version?</p><h2>Share your drawing, sample or requirement.</h2><p>We can review size, material, finish, quantity, packaging and quality expectations with you.</p></div><a href="#contact" className="hero-btn hero-btn-primary">Start an enquiry <FiArrowUpRight /></a></section>
  </main>
}
