import { FiArrowUpRight, FiCheck, FiCpu, FiLayers, FiSettings, FiTool } from 'react-icons/fi'

export function PremiumHome({ onOpenPage }: { onOpenPage: (page: string) => void }) {
  return <>
    <section className="about-preview reveal-section"><div><p className="eyebrow">About Company</p><h2>Manufacturing with accuracy, control and consistency.</h2></div><div><p>SKR METAL INDUSTRIES PVT. LTD. manufactures umbrella ribs and frames along with precision-machined metal components for industrial applications. Our operations are built on technical expertise, reliability and long-term business relationships.</p><button className="text-link" onClick={() => onOpenPage('profile')}>About SKR <FiArrowUpRight /></button></div></section>
    <section className="product-showcase reveal-section"><div className="section-heading premium-heading"><div><p className="eyebrow">What We Do</p><h2>Two divisions. Focused manufacturing.</h2></div><button className="text-link" onClick={() => onOpenPage('products')}>Explore products <FiArrowUpRight /></button></div><div className="home-product-grid"><article><FiLayers /><span>Umbrella Division</span><h3>Ribs and frames for every configuration</h3><p>2 Fold, 3 Fold, Solid, Piano and Golf umbrella frames manufactured for strength, flexibility and smooth functionality.</p></article><article><FiCpu /><span>Engineering &amp; Hardware</span><h3>Precision industrial components</h3><p>ATM parts, printer components, valve fittings, control panel components and pressure gauge meter parts.</p></article><article><FiSettings /><span>Custom Manufacturing</span><h3>Made to drawings and specifications</h3><p>Components produced from technical drawings, customer samples and custom manufacturing requirements.</p></article></div></section>
    <section className="infrastructure-section reveal-section"><div className="infrastructure-copy"><p className="eyebrow">Technical Infrastructure</p><h2>Equipment that supports controlled production.</h2><p>Our facility is equipped with CNC machines, VMC machines, EDM machines and specialised purpose machines. This enables tight tolerances, efficient workflow, consistent output quality and bulk production capability.</p><button className="text-link" onClick={() => onOpenPage('capabilities')}>View capabilities <FiArrowUpRight /></button></div><div className="infrastructure-grid"><article><b>01</b><h3>CNC Machining</h3><span>Precision production for drawing-led components</span></article><article><b>02</b><h3>VMC &amp; EDM</h3><span>Accurate machining and technical process control</span></article><article><b>03</b><h3>SPM Systems</h3><span>Efficient output for bulk and custom requirements</span></article></div></section>
    <section className="industry-section reveal-section"><div className="industry-image image-cover" role="img" aria-label="Precision manufacturing equipment" /><div className="industry-copy"><p className="eyebrow">Industries We Serve</p><h2>Components for essential industrial applications.</h2><div className="industry-tags"><span>Umbrella Manufacturing</span><span>ATM Machines</span><span>Printer Assemblies</span><span>Electrical &amp; Control Panels</span><span>Valve &amp; Fittings</span><span>Pressure Instrumentation</span><span>Hardware &amp; Joinery</span><span>General Engineering</span></div><button className="hero-btn hero-btn-primary" onClick={() => onOpenPage('contact')}>Discuss your requirement <FiArrowUpRight /></button></div></section>
    <section className="quality-feature reveal-section"><div className="quality-copy"><p className="eyebrow">Quality Focus</p><h2>Repeatable output, every batch.</h2><p>Our controlled production processes support high dimensional accuracy, production consistency, repeatability and reliable batch quality. Every stage is monitored for dimensional accuracy, surface finish and consistent quality.</p></div><div className="quality-cards"><article><FiTool /><h3>Process control</h3><p>Practical planning from technical requirement to finished component.</p></article><article><FiCheck /><h3>Quality verification</h3><p>Inspection-led checks for precise, consistent manufacturing output.</p></article></div></section>
    <section className="contact-cta reveal-section"><div><p className="eyebrow">Start A Conversation</p><h2>Looking for a reliable manufacturing partner?</h2><p>Contact us for product enquiries, quotations and technical discussions. Share your drawing, sample, material, quantity and application requirement.</p></div><button className="cta-circle" onClick={() => onOpenPage('contact')} aria-label="Start an enquiry"><FiArrowUpRight /></button></section>
  </>
}
